# Generated by Django 3.2.9 on 2022-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_auto_20200121_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('da', 'Danish'), ('id', 'Indonesian'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sr', 'Serbian'), ('en', 'Somali'), ('es', 'Spanish'), ('tr', 'Turkish')], default='de', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
